
/* Isolated CHAT_90 admin console. Requires the normal CHAT_90 session first. */
(() => {
  const PIN='7879';
  const pinModal=document.getElementById('adminPinModal'), pinInput=document.getElementById('adminPinInput'), pinStatus=document.getElementById('adminPinStatus');
  const panel=document.getElementById('adminPanel'), commandInput=document.getElementById('adminCommandInput'), commandSend=document.getElementById('adminCommandSend');
  const output=document.getElementById('adminOutput'), suggestions=document.getElementById('adminSuggestions');
  const close=document.getElementById('adminPanelClose'), cancel=document.getElementById('adminPinCancel'), submit=document.getElementById('adminPinSubmit');
  const mediaButton=document.getElementById('adminAnnoyMediaButton'), mediaInput=document.getElementById('adminAnnoyMediaInput'), confirm=document.getElementById('adminConfirm');
  const confirmName=document.getElementById('adminConfirmName'), confirmNo=document.getElementById('adminConfirmNo'), confirmYes=document.getElementById('adminConfirmYes');
  let pendingBroadcast=null;
  const commands=['/help','/users','/bans','/ban ','/unban ','/history ','/clear','/announce ','/effect ','/effect all ','/effects','/annoy all','/glow ','/kick ','/whois ','/find ','/status','/mute ','/unmute ','/delete '];
  function bridge(){return window.Chat90Bridge;}
  function print(text,kind=''){const row=document.createElement('div');row.className=kind;row.textContent=`[${new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}] ${text}`;output.appendChild(row);output.scrollTop=output.scrollHeight;}
  function showSuggestions(){const raw=commandInput.value.toLowerCase();const q=raw.startsWith('/')?raw:'/'+raw;if(!raw){suggestions.hidden=true;return;}const list=commands.filter(c=>c.startsWith(q)||c.slice(1).startsWith(raw));suggestions.innerHTML=list.map(c=>`<button class="admin-suggestion" type="button" data-cmd="${c}">${c}</button>`).join('');suggestions.hidden=!list.length;suggestions.querySelectorAll('[data-cmd]').forEach(b=>b.addEventListener('click',()=>{commandInput.value=b.dataset.cmd;commandInput.focus();}));}
  function sendCommand(raw){const text=String(raw||'').trim();if(!text)return;if(text.toLowerCase()==='/annoy all'){commandInput.value='/annoy all';confirmName.textContent='COMMAND ACTIVE • /annoy all';confirm.hidden=true;mediaInput?.click();return;} if(!text.startsWith('/')){print('Commands must start with /. Try /help.','bad');return;} const bits=text.slice(1).match(/(?:[^\s"]+|"[^"]*")+/g)||[]; const command=bits.shift()||''; const args=bits.map(x=>x.replace(/^"|"$/g,'')); bridge()?.send({type:'adminCommand',command,args}); print(`> ${text}`); commandInput.value='';suggestions.hidden=true;}
  function unlock(){ if(pinInput.value!==PIN){pinStatus.textContent='PIN REJECTED — TRY AGAIN.';pinInput.select();return;} if(!bridge()?.isConnected()){pinStatus.textContent='CHAT_90 CONNECTION NOT READY.';return;} bridge().send({type:'adminAuth',pin:pinInput.value}); pinStatus.textContent='VERIFYING PRIVILEGE...'; }
  function openPin(){ if(!window.chat90ChatOpen){ /* harmless */ } pinModal.hidden=false;pinInput.value='';pinStatus.textContent='';setTimeout(()=>pinInput.focus(),30); }
  function closePin(){pinModal.hidden=true;}
  function openPanel(){closePin();panel.hidden=false;window.chat90AdminActive=true;bridge()?.setAdminProfile(true);bridge()?.render();print('ADMIN SESSION ACTIVE — RED PRIVILEGE ONLINE.','ok');commandInput.focus();}
  function closePanel(){panel.hidden=true;window.chat90AdminActive=false;pendingBroadcast=null;confirm.hidden=true;}
  submit?.addEventListener('click',unlock);pinInput?.addEventListener('keydown',e=>{if(e.key==='Enter')unlock();if(e.key==='Escape')closePin();});cancel?.addEventListener('click',closePin);close?.addEventListener('click',closePanel);commandSend?.addEventListener('click',()=>sendCommand(commandInput.value));commandInput?.addEventListener('keydown',e=>{if(e.key==='Enter')sendCommand(commandInput.value);if(e.key==='Escape')closePanel();});commandInput?.addEventListener('input',showSuggestions);
  document.querySelectorAll('[data-admin-cmd]').forEach(b=>b.addEventListener('click',()=>sendCommand(b.dataset.adminCmd)));
  mediaButton?.addEventListener('click',()=>mediaInput?.click());
  mediaInput?.addEventListener('change',async()=>{const file=mediaInput.files?.[0];mediaInput.value='';if(!file)return;if(file.size>24*1024*1024){print('MEDIA TOO LARGE — 24 MB MAX.','bad');return;}const data=await new Promise((res,rej)=>{const r=new FileReader();r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file);});pendingBroadcast={data,type:file.type.startsWith('video/')?'video':'audio',name:file.name};confirmName.textContent=`/annoy all  •  ${file.name}`;confirm.hidden=false;});
  confirmNo?.addEventListener('click',()=>{pendingBroadcast=null;confirm.hidden=true;});
  confirmYes?.addEventListener('click',()=>{if(!pendingBroadcast)return;bridge()?.send({type:'adminBroadcast',media:pendingBroadcast.data,mediaType:pendingBroadcast.type,name:pendingBroadcast.name});print(`ANN0Y ALL ACTIVATED • ${pendingBroadcast.name}`,'ok');pendingBroadcast=null;confirm.hidden=true;});
  window.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='p'){e.preventDefault();if(panel.hidden)openPin();else closePanel();}});
  window.addEventListener('chat90-admin-result',e=>{const p=e.detail||{};if(p.ok)print(p.message||'COMMAND COMPLETE.','ok');else print(p.message||'COMMAND FAILED.','bad');if(p.command==='users'&&Array.isArray(p.users)){p.users.forEach(u=>{const b=document.createElement('button');b.className='admin-user-chip';b.type='button';b.textContent=`${u.username} • ${u.role||'MEMBER'}`;b.title='Account is active — click to inspect';b.addEventListener('click',()=>{commandInput.value=`/whois ${u.username}`;sendCommand(commandInput.value);});output.appendChild(b);});output.scrollTop=output.scrollHeight;}if(p.command==='history'&&Array.isArray(p.history)){p.history.forEach(m=>print(`${m.username||'SYSTEM'}: ${m.text||'[MEDIA]'}`));}if(p.command==='bans'&&Array.isArray(p.bans)){p.bans.forEach(b=>{const row=document.createElement('button');row.className='admin-user-chip';row.type='button';row.textContent=`BANNED • ${b.username} • UNTIL ${new Date(b.until).toLocaleString()}`;row.title='Click to unban this account';row.addEventListener('click',()=>sendCommand(`/unban ${b.username}`));output.appendChild(row);});output.scrollTop=output.scrollHeight;}if(p.command==='effects')print(p.message||'');if(p.profile){const b=document.createElement('div');b.className='admin-account-confirm';b.textContent=`ACCOUNT VERIFIED • ${p.profile.username} • ${p.profile.role||'MEMBER'}`;output.appendChild(b);output.scrollTop=output.scrollHeight;}});
  window.addEventListener('chat90-admin-auth',e=>{const p=e.detail||{};if(p.ok)openPanel();else{pinStatus.textContent=p.message||'PIN REJECTED.';}});
  window.addEventListener('chat90-admin-broadcast',e=>{const p=e.detail||{}; if(p.media){const el=p.mediaType==='video'?document.createElement('video'):new Audio();if(p.mediaType==='video'){el.src=p.media;el.autoplay=true;el.controls=true;el.playsInline=true;el.className='admin-broadcast-video';document.body.appendChild(el);el.style='position:fixed;inset:0;z-index:10001;width:100%;height:100%;object-fit:contain;background:#000d;';el.addEventListener('ended',()=>el.remove(),{once:true});}else{el.src=p.media;el.volume=1;el.autoplay=true;el.addEventListener('ended',()=>el.remove(),{once:true});el.play().catch(()=>{});} } });
  window.addEventListener('chat90-admin-history-sync',()=>bridge()?.render());
  window.addEventListener('chat90-admin-open-pin',openPin);
  window.Chat90Admin={open:openPin,close:closePanel};
})();
